version: "1.0.{build}"
image: Visual Studio 2019
branches:
  only:
    - feature/add_travis
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

nuget:
  disable_publish_on_pr: true

# Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./IqOptionApi.sln --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build ./src/IqOptionApi.NET/IqOptionApi.NET.csproj

test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./tests/IqOptionApi.Tests/IqOptionApi.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd tests/IqOptionApi.Tests
  - cmd: dotnet test

after_test:
  - cmd: cd ./src/IqOptionApi.NET
  - cmd: dotnet pack --configuration release -o Build\Packages\

artifacts:
  - path: Build\Packages\*nupkg

# any cleanup in here
deploy:
  - provider: NuGet
    api_key:
      secure: iAOTJg7HXhC5IC1IGU186QfHt46ixII7hlz/7d2kbc5iOBG+WT2rSRbf4RtcafyN
    skip_symbols: false
    artifact: /.*\.(nupkg|snupkg)/
    on:
      branch: feature/add_travis
      appveyor_repo_tag: true
