version: 2.0.{build}
image: Visual Studio 2017
branches:
  only:
  - develop

install:
# Install repo specific stuff here

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore IqOptionApi.Net.sln --verbosity m

build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build .src/IqOptionApi/IqOptionApi.csproj

configuration: Release
platform: Any CPU
build:
  project: IqOptionApi.Net.sln
  verbosity: minimal
before_package:
- cmd: nuget restore
test_script:
  - cmd: dotnet restore src/IqOptionApi.Tests/IqOptionApi.Tests.csproj
  - cmd: cd src/IqOptionApi.Tests
  - cmd: dotnet test
on_finish :
  # any cleanup in here
deploy: off
