version: 2.0.{build}
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
build:
  project: IqOptionApi.Net.sln
  verbosity: minimal
before_package:
- cmd: nuget restore
test_script:
- cmd: dotnet test src\IqOptionApi.Tests\IqOptionApi.Tests.csproj
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

deploy:
  # - provider: NuGet
  #   api_key:
  #     secure: oy2fyfz3uylh5jt2k6wa4mjxqhdbvbrurlrpxj63lcxy6e
  #   skip_symbols: false
  #   on:
  #     branch: master

  # - provider: GitHub
  #   artifact: /.*\.(nupkg|zip)/
  #   auth_token:
  #     secure: f+y+1670d0857ea05ca8d273a2e0fd47d92e28dda0f8
  #   tag: v$(appveyor_build_version)
  #   draft: true
  #   prerelease: false
  #   on:
  #     branch: master
