version: "2.1.{build}"
image: Visual Studio 2019
branches:
  only:
    - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
  - ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")

    {
      Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME).$($env:APPVEYOR_BUILD_NUMBER)"
    }

    else

    {
      Update-AppveyorBuild -Version "2.1.$($env:APPVEYOR_BUILD_NUMBER)-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
    }

nuget:
  disable_publish_on_pr: true

assembly_info:
  # Patch true ensures that the assemblies version number
  # gets set to the build version number
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./IqOptionApi.sln --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build ./src/IqOptionApi.NET/IqOptionApi.NET.csproj --configuration release

after_build:
  - cmd: dotnet pack ./src/IqOptionApi.NET/IqOptionApi.NET.csproj --configuration release -o Build\Packages\ -p:PackageVersion='{version}'

test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./tests/IqOptionApi.Tests/IqOptionApi.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd tests/IqOptionApi.Tests
  - cmd: dotnet test

artifacts:
  - path: Build\Packages\*nupkg

# any cleanup in here
deploy:
  - provider: NuGet
    api_key:
      secure: PD+Mb+nDiji71lFSy6wzQr+k796j3KBXsZswzX0p+LBZ+orVn+yPI/soLlHxfexz
    skip_symbols: false
    artifact: /.*\.(nupkg|snupkg)/
    appveyor_repo_tag: true
    on:
      branch: master
