init:
  - ps: git config --global core.autocrlf input
  - ps: '[Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")'
  - ps: Restart-Service docker

image: Visual Studio 2019

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true