version: 2.1
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build ./IqOptionApi.Net.sln.sln

deployment:
  # master:
  #   branch: master
  #   commands:
  #     - sh script/publish-azure
  #     - sh script/publish-dockerhub